
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tukar.landing-page
    ports:
      - "3005:3005"
    volumes:
      - .:/app            # Mount kode lokal ke container
      - /app/node_modules # Jangan share node_modules host <-> container
    environment:
      - NODE_ENV=production
    command: npm run start
